### PR TITLE
fix comics duplucating per genre

### LINKED ISSUE #39: duplicate comic for each genre in get_comics
The join
https://github.com/BKSalman/musawarah/blob/4482caa3e3269a640767cabb684c44d223b16931/src/comics/routes.rs#L250
in
https://github.com/BKSalman/musawarah/blob/4482caa3e3269a640767cabb684c44d223b16931/src/comics/routes.rs#L247-L253
is causing each comic to appear once for each genre it has.

### PR DESCRIPTION
**Pull request by mohad12211**
would be better if we didn't join on the genres table in the first place, but I couldn't figure out how to join it conditionally
fixes #39

### CODE REVIEW

**Comment by BKSalman** [comment]
> but I couldn't figure out how to join it conditionally

can't you just do it like this? https://github.com/BKSalman/musawarah/blob/bd615bc94f68ca00b71b75f0b9464d79490da61a/src/comics/routes.rs#L256


so it would be something like: 
```rust
    if params.genre.is_some() {
        comics_query = comics_query.left_join(comic_genres_mapping::table.inner_join(comic_genres::table)); 
    }
// the rest
```

**Comment by mohad12211** [comment]
> > but I couldn't figure out how to join it conditionally
> 
> 
> 
> can't you just do it like this? https://github.com/BKSalman/musawarah/blob/bd615bc94f68ca00b71b75f0b9464d79490da61a/src/comics/routes.rs#L256
> 
> 
> 
> 
> 
> so it would be something like: 
> 
> ```rust
> 
>     if params.genre.is_some() {
> 
>         comics_query = comics_query.left_join(comic_genres_mapping::table.inner_join(comic_genres::table)); 
> 
>     }
> 
> // the rest
> 
> ```
> 
> 

https://matrix.to/#/!lNGJpfiFVovXFJYmwx:matrix.org/$16890263181bDNPr:gitter.im?via=mozilla.org&via=gitter.im&via=matrix.org

**Comment by BKSalman** [comment]
you mean we should do it by calling `belonging_to` instead of joining?

**Comment by mohad12211** [comment]
> > but I couldn't figure out how to join it conditionally
> 
> can't you just do it like this?
> 
> https://github.com/BKSalman/musawarah/blob/bd615bc94f68ca00b71b75f0b9464d79490da61a/src/comics/routes.rs#L256
> 
> so it would be something like:
> 
> ```rust
>     if params.genre.is_some() {
>         comics_query = comics_query.left_join(comic_genres_mapping::table.inner_join(comic_genres::table)); 
>     }
> // the rest
> ```
```rust
error[E0308]: mismatched types
   --> src/comics/routes.rs:255:24
    |
247 |       let mut comics_query = comics::table
    |  ____________________________-
248 | |         .inner_join(users::table)
249 | |         .left_join(comic_ratings::table)
250 | |         .filter(comics::id.gt(params.min_id))
251 | |         .filter(comics::id.lt(params.max_id))
252 | |         .into_boxed();
    | |_____________________- expected due to this value
...
255 |           comics_query = comics_query
    |  ________________________^
256 | |             .left_join(comic_genres_mapping::table.inner_join(comic_genres::table))
257 | |             .filter(comic_genres::id.eq(genre_filter));
    | |______________________________________________________^ expected `schema::comics::table`, found `JoinOn<Join<table, table, Inner>, Grouped<...>>`
    |
    = note: expected struct `BoxedSelectStatement<'_, ((Uuid, Text, Nullable<Text>, Timestamptz, Nullable<Timestamptz>, Bool, Nullable<Timestamptz>, Nullable<Text>, Nullable<Text>, Uuid), ..., ...), ..., ...>` (`schema::comics::table`)
            the full type name has been written to '/home/mohad/projects/musawarah/target/debug/deps/musawarah-acf8892a4e68bdac.long-type-8047677714729799317.txt'
               found struct `BoxedSelectStatement<'_, ((Uuid, Text, Nullable<Text>, Timestamptz, Nullable<Timestamptz>, Bool, Nullable<Timestamptz>, Nullable<Text>, Nullable<Text>, Uuid), ..., ...), ..., ...>` (`JoinOn<Join<table, table, Inner>, Grouped<...>>`)
            the full type name has been written to '/home/mohad/projects/musawarah/target/debug/deps/musawarah-acf8892a4e68bdac.long-type-11337374463602616263.txt'
```
from gitter: 
```
weiznich
That's not supported because diesel needs to know the from clause of queries statically to allow checking the query at compile time.
mohad12211 (mohad12211)
any idea how can I achieve the wanted result 
weiznich
Use two separate queries.
```

**Comment by mohad12211** [comment]
I wouldn't worry about it _for now_

**Comment by BKSalman** [comment]
I would say leave it for later, because it's not that big of a deal now.

later :tm:

**Comment by BKSalman** [comment]
LGTM LGTM

**Pull request merged**
